vpc-name            = "Jenkins-vpc"
igw-name            = "Jenkins-igw"
subnet-name         = "Jenkins-subnet"
subnet-name2        = "Jenkins-subnet2"
security-group-name = "Jenkins-sg"
rt-name2            = "Jenkins-route-table2"
cluster-name        = "Geemu-EKS-Cluster"
eksnode-group-name  = "Geemu-Node-Group"